%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% GenFtr generate features from files
%   Author: Jerry (Zengjie) Zhang
%   Date: 2018.11.23
% 
% Function prototype: 
%   [ClsFtrs, CtcFtrs, FreFtrs] = GenFtr(DtHdl, SegConf, FtrConf, Mode, ...
%                                   RtPath);
%
% Parameter(s):
%   1. 'DtHdl' is the database handle generated by function 'GenList';
%   2. 'SegConf' is the structure to store data segmentation hyper-parameters;
%   3. 'FtrConf' is the structure to store feature extraction hyper-parameters;
%   4. 'Mode' denote the way that features are extracted; Tolerate modes are:
%    "feature": which extracts features for norminal classifiers;
%    "rnn": which extracts sequence segments for rnns;
%    "cnn-stft": which extracts short-time fourier transformation features 
%                for cnns;
%    "cnn-wlt": which extracts wavelet transformation features for cnns;
%   5. 'RtPath' stores the root path of the dataset.
%
% Returned value(s):
%   'ClsFtrs', 'CtcFtrs' and 'FreFtrs' are 3-dimensional tensors to store 
%   features of collisions, contacts and free cases, respectively. The 
%   dimensions are denoted as [joints, feature items, feature elements]


function [FtrsOut, Tims] = GenFtrOnline(FilePath, SegConf, FtrConf, FltConf, RtPath, Out)

if FtrConf.flag == 1

    switch FtrConf.Mode
    case "feature"
        Sz =  max(size(FtrConf.FtrSlc));
    case "rnn"
        Sz = SegConf.WinSz;
    case "cnn-stft"
        Sz = fix((SegConf.WinSz-FtrConf.Ovl)/(FtrConf.SegSz-FtrConf.Ovl)) * (FtrConf.NSTFT/2+1);
    case "cnn-wlt"
        Sz = SegConf.WinSz * FtrConf.NWLT;
    otherwise
    end

    fprintf('Generating features online ... ');

    Lt = size(SegConf.SlcMtr);
    JME = load([char(FilePath), '/JK_MsrExtTrq.mat']);
    JSZ = length(JME.MsrExtTrq)-SegConf.WinSz;
    JMM = 1:JSZ;
    Ftrs = zeros(Lt(2), length(JMM), Sz);
    Tims = zeros(length(JMM), 1);

    DSS = load([RtPath, '/PureSgn/DataStillSpl.mat']);
    
    dp = 'process completed by 0 ...';
    fprintf(dp);

    for i = JMM
        [Ftrs(:, i, :), Tims(i)] = Sgn2Ftr(abs(PrePrcs(JME.MsrExtTrq(2:8,i+1:i+SegConf.WinSz)', DSS.DataStillSpl(2:8,1:SegConf.WinSz)', FltConf))*SegConf.SlcMtr, ...
            0, 1, SegConf, FtrConf, [Lt(2), Sz]);
        ndp = ['process completed by ', num2str(i), ' Out of ', num2str(length(JMM)), ' ...'];
        fprintf([repmat('\b',1,max(size(dp))), ndp]);
        dp = ndp;
    end

    switch Out
    case "3D"
        FtrsOut = Ftrs;
    case "2D"
        Sz = size(Ftrs);
        FtrsOut = zeros(Sz(2), Sz(1)*Sz(3));
        for i = 1:Sz(1)
            FtrsOut(:, (i-1)*Sz(3)+1:i*Sz(3)) = reshape(Ftrs(i,:,:), [Sz(2), Sz(3)]);
        end
    otherwise
    disp('Invalid output style, use "2D" instead.');    
    end
    disp(' Complete.');

else
    disp('Program aborted.');
end













