%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% GenFtr generate features from files
%   Author: Jerry (Zengjie) Zhang
%   Date: 2018.11.23
% 
% Function prototype: 
%   [ClsFtrs, CtcFtrs, FreFtrs] = GenFtr(DtHdl, SegConf, FtrConf, Mode, ...
%                                   RtPath);
%
% Parameter(s):
%   1. 'DtHdl' is the database handle generated by function 'GenList';
%   2. 'SegConf' is the structure to store data segmentation hyper-parameters;
%   3. 'FtrConf' is the structure to store feature extraction hyper-parameters;
%   4. 'Mode' denote the way that features are extracted; Tolerate modes are:
%    "feature": which extracts features for norminal classifiers;
%    "rnn": which extracts sequence segments for rnns;
%    "cnn-stft": which extracts short-time fourier transformation features 
%                for cnns;
%    "cnn-wlt": which extracts wavelet transformation features for cnns;
%   5. 'RtPath' stores the root path of the dataset.
%
% Returned value(s):
%   'ClsFtrs', 'CtcFtrs' and 'FreFtrs' are 3-dimensional tensors to store 
%   features of collisions, contacts and free cases, respectively. The 
%   dimensions are denoted as [joints, feature items, feature elements]


function [ClsFtrsOut, CtcFtrsOut, FreFtrsOut, ClsTims, CtcTims, FreTims] = GenFtr(DtHdl, SegConf, FtrConf, FltConf, RtPath, Out)

if FtrConf.flag == 1

    switch FtrConf.Mode
    case "feature"
        Sz =  max(size(FtrConf.FtrSlc));
    case "rnn"
        Sz = SegConf.WinSz;
    case "cnn-stft"
        Sz = fix((SegConf.WinSz-FtrConf.Ovl)/(FtrConf.SegSz-FtrConf.Ovl)) * (FtrConf.NSTFT/2+1);
    case "cnn-wlt"
        Sz = SegConf.WinSz * FtrConf.NWLT;
    otherwise
    end

    fprintf('Generating features ... ');

    Lt = size(SegConf.SlcMtr);

    ClsFtrs = zeros(Lt(2), DtHdl.NCls, Sz);
    CtcFtrs = zeros(Lt(2), DtHdl.NCtc, Sz);
    FreFtrs = zeros(Lt(2), DtHdl.NFre, Sz);
    ClsTims = zeros(DtHdl.NCls, 1);
    CtcTims = zeros(DtHdl.NCtc, 1);
    FreTims = zeros(DtHdl.NFre, 1);

    DSS = load([RtPath, '/PureSgn/DataStillSpl.mat']);
    ItmPntCls = 0;
    ItmPntCtc = 0;
    ItmPntFre = 0;
    dp = 'process completed by 0%% ...';
    fprintf(dp);
    for i = 1:max(size(DtHdl.DirCls))
        JME = load([char(DtHdl.DirCls(i)), '/JK_MsrExtTrq.mat']);
        JMM = load([char(DtHdl.DirCls(i)), '/JK_moments.mat']);
%        JMC = load([char(DtHdl.DirCls(i)), '/JK_Jcb.mat']);
%        JME = JMC'*JMT;
        
        [ClsFtrs(:, ItmPntCls+1:ItmPntCls+DtHdl.CntCls(i), :), ClsTims(ItmPntCls+1:ItmPntCls+DtHdl.CntCls(i), 1)] = Sgn2Ftr( ...
                abs(PrePrcs(JME.MsrExtTrq(2:8,:)', DSS.DataStillMean(2:8,:)', FltConf))*SegConf.SlcMtr, ...
                JMM.JK_moments, DtHdl.CntCls(i), ...
                SegConf, FtrConf, [Lt(2), Sz]);        
        
        [FreFtrs(:, ItmPntFre+1:ItmPntFre+DtHdl.CntFre(i), :), FreTims(ItmPntFre+1:ItmPntFre+DtHdl.CntFre(i), 1)] = Sgn2Ftr( ...
                abs(PrePrcs(JME.MsrExtTrq(2:8,:)', DSS.DataStillMean(2:8,:)', FltConf))*SegConf.SlcMtr, ...
                ItplVec(JMM.JK_moments), DtHdl.CntFre(i), ...
                SegConf, FtrConf, [Lt(2), Sz]);

        ItmPntCls = ItmPntCls + DtHdl.CntCls(i);
        ItmPntFre = ItmPntFre + DtHdl.CntFre(i);

        ndp = ['process completed by ', num2str(roundn(100*ItmPntFre/DtHdl.NFre, -2)), '%% ...'];
        fprintf([repmat('\b',1,max(size(dp))-1), ndp]);
        dp = ndp;
    end
    for k = 1:max(size(DtHdl.DirCtc))
        JME = load([char(DtHdl.DirCtc(k)), '/JK_MsrExtTrq.mat']);
        JMM = load([char(DtHdl.DirCtc(k)), '/JK_moments.mat']);
  %      JMC = load([char(DtHdl.DirCls(i)), '/JK_Jcb.mat']);
  %      JME = JMC'*JMT;
        
        [CtcFtrs(:, ItmPntCtc+1:ItmPntCtc+DtHdl.CntCtc(k), :), CtcTims(ItmPntCtc+1:ItmPntCtc+DtHdl.CntCtc(k), 1)] = Sgn2Ftr( ...
                abs(PrePrcs(JME.MsrExtTrq(2:8,:)', DSS.DataStillMean(2:8,:)', FltConf))*SegConf.SlcMtr, ...
                JMM.JK_moments, DtHdl.CntCtc(k), ...
                SegConf, FtrConf, [Lt(2), Sz]);
        
        [FreFtrs(:, ItmPntFre+1:ItmPntFre+DtHdl.CntFre(i+k), :), FreTims(ItmPntFre+1:ItmPntFre+DtHdl.CntFre(i+k), 1)] = Sgn2Ftr( ...
                abs(PrePrcs(JME.MsrExtTrq(2:8,:)', DSS.DataStillMean(2:8,:)', FltConf))*SegConf.SlcMtr, ...
                ItplVec(JMM.JK_moments), DtHdl.CntFre(i+k), ...
                SegConf, FtrConf, [Lt(2), Sz]);

        ItmPntCtc = ItmPntCtc + DtHdl.CntCtc(k);
        ItmPntFre = ItmPntFre + DtHdl.CntFre(i+k);

        ndp = ['process completed by ', num2str(roundn(100*ItmPntFre/DtHdl.NFre, -2)), '%% ...'];
        fprintf([repmat('\b',1,max(size(dp))-1), ndp]);
        dp = ndp;
    end
    
    switch Out
    case "3D"
        ClsFtrsOut = ClsFtrs;
        CtcFtrsOut = CtcFtrs;
        FreFtrsOut = FreFtrs;
    case "2D"
        SzCls = size(ClsFtrs);
        SzCtc = size(CtcFtrs);
        SzFre = size(FreFtrs);
        ClsFtrsOut = zeros(SzCls(2), SzCls(1)*SzCls(3));
        CtcFtrsOut = zeros(SzCtc(2), SzCtc(1)*SzCtc(3));
        FreFtrsOut = zeros(SzFre(2), SzFre(1)*SzFre(3));
        for i = 1:SzCls(1)
            ClsFtrsOut(:, (i-1)*SzCls(3)+1:i*SzCls(3)) = reshape(ClsFtrs(i,:,:), [SzCls(2), SzCls(3)]);
            CtcFtrsOut(:, (i-1)*SzCtc(3)+1:i*SzCtc(3)) = reshape(CtcFtrs(i,:,:), [SzCtc(2), SzCls(3)]);
            FreFtrsOut(:, (i-1)*SzFre(3)+1:i*SzFre(3)) = reshape(FreFtrs(i,:,:), [SzFre(2), SzCls(3)]);
        end
    otherwise
    disp('Invalid output style, use "2D" instead.');    
    end
    disp(' Complete.');

else
    disp('Program aborted.');
end













